import type { SubclassDefinition } from "@/types/game";

// Two subclasses per role. Add more later by pushing another
// SubclassDefinition with the same `role` — nothing else needs to change,
// the hero/talent/combat systems are role-agnostic.
export const SUBCLASSES: SubclassDefinition[] = [
  {
    id: "guerrier",
    role: "DPS",
    name: "Guerrier",
    description: "Combattant au corps-à-corps misant sur les dégâts bruts.",
    strengths: "Dégâts élevés, montée en puissance rapide.",
    weaknesses: "Peu de survie face aux dégâts de zone.",
    baseStats: { hp: 80, atk: 16, def: 6, spd: 10 },
    statGrowthPerLevel: { hp: 8, atk: 2.2, def: 0.6, spd: 0.3 },
    talentTree: [
      {
        id: "guerrier-force-brute",
        name: "Force brute",
        description: "+ dégâts d'attaque par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { atk: 1.5 },
      },
      {
        id: "guerrier-cuir-durci",
        name: "Cuir durci",
        description: "+ défense par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { def: 1 },
      },
      {
        id: "guerrier-fureur",
        name: "Fureur",
        description: "+ vitesse par rang, nécessite Force brute.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "guerrier-force-brute",
        statBonusPerRank: { spd: 1, atk: 1 },
      },
      {
        id: "guerrier-parade",
        name: "Parade",
        description: "+ défense et + vie par rang, nécessite Cuir durci.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "guerrier-cuir-durci",
        statBonusPerRank: { def: 1, hp: 4 },
      },
      {
        id: "guerrier-acharnement",
        name: "Acharnement",
        description: "+ dégâts et + vie par rang, ultime offensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "guerrier-fureur",
        statBonusPerRank: { atk: 4, hp: 10 },
      },
      {
        id: "guerrier-titan",
        name: "Titan",
        description: "+ défense et + vie par rang, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "guerrier-parade",
        statBonusPerRank: { def: 4, hp: 16 },
      },
      {
        id: "guerrier-legende",
        name: "Légende vivante",
        description: "+ dégâts et + vie, nécessite Acharnement et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "guerrier-acharnement",
        requiresStarRank: 3,
        statBonusPerRank: { atk: 6, hp: 14 },
      },
    ],
  },
  {
    id: "archer",
    role: "DPS",
    name: "Archer",
    description: "Tireur agile qui frappe vite et de loin.",
    strengths: "Grande vitesse d'attaque, très mobile.",
    weaknesses: "Très fragile, meurt vite si submergé.",
    baseStats: { hp: 60, atk: 14, def: 3, spd: 16 },
    statGrowthPerLevel: { hp: 5, atk: 2, def: 0.3, spd: 0.6 },
    talentTree: [
      {
        id: "archer-oeil-de-faucon",
        name: "Œil de faucon",
        description: "+ dégâts d'attaque par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { atk: 1.3 },
      },
      {
        id: "archer-pas-legers",
        name: "Pas légers",
        description: "+ vitesse par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { spd: 1.2 },
      },
      {
        id: "archer-tir-rapide",
        name: "Tir rapide",
        description: "+ dégâts et + vitesse par rang, nécessite Œil de faucon.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "archer-oeil-de-faucon",
        statBonusPerRank: { atk: 1.5, spd: 0.5 },
      },
      {
        id: "archer-esquive",
        name: "Esquive",
        description: "+ vitesse et + défense par rang, nécessite Pas légers.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "archer-pas-legers",
        statBonusPerRank: { spd: 1, def: 1 },
      },
      {
        id: "archer-pluie-de-fleches",
        name: "Pluie de flèches",
        description: "+ dégâts important, ultime offensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "archer-tir-rapide",
        statBonusPerRank: { atk: 6 },
      },
      {
        id: "archer-ombre-furtive",
        name: "Ombre furtive",
        description: "+ vitesse et + vie, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "archer-esquive",
        statBonusPerRank: { spd: 3, hp: 12 },
      },
      {
        id: "archer-tempete-de-fleches",
        name: "Tempête de flèches",
        description: "+ dégâts et + vitesse, nécessite Pluie de flèches et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "archer-pluie-de-fleches",
        requiresStarRank: 3,
        statBonusPerRank: { atk: 7, spd: 2 },
      },
    ],
  },
  {
    id: "pretre",
    role: "HEAL",
    name: "Prêtre",
    description: "Soigneur misant sur les soins directs et la résistance.",
    strengths: "Soins puissants, bonne survie.",
    weaknesses: "Dégâts infligés très faibles.",
    baseStats: { hp: 70, atk: 6, def: 8, spd: 9 },
    statGrowthPerLevel: { hp: 7, atk: 0.5, def: 0.8, spd: 0.3 },
    talentTree: [
      {
        id: "pretre-lumiere-apaisante",
        name: "Lumière apaisante",
        description: "+ vie max par rang (soins plus efficaces en valeur).",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { hp: 6 },
      },
      {
        id: "pretre-devotion",
        name: "Dévotion",
        description: "+ défense par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { def: 1 },
      },
      {
        id: "pretre-zele",
        name: "Zèle",
        description: "+ vitesse par rang, nécessite Lumière apaisante.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "pretre-lumiere-apaisante",
        statBonusPerRank: { spd: 1 },
      },
      {
        id: "pretre-foi-ardente",
        name: "Foi ardente",
        description: "+ dégâts et + défense par rang, nécessite Dévotion.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "pretre-devotion",
        statBonusPerRank: { atk: 1, def: 1 },
      },
      {
        id: "pretre-sanctuaire",
        name: "Sanctuaire",
        description: "+ vie et + défense, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "pretre-zele",
        statBonusPerRank: { hp: 15, def: 3 },
      },
      {
        id: "pretre-martyr",
        name: "Martyr",
        description: "+ vie et + dégâts, ultime offensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "pretre-foi-ardente",
        statBonusPerRank: { hp: 10, atk: 4 },
      },
      {
        id: "pretre-benediction-divine",
        name: "Bénédiction divine",
        description: "+ vie et + défense, nécessite Sanctuaire et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "pretre-sanctuaire",
        requiresStarRank: 3,
        statBonusPerRank: { hp: 20, def: 4 },
      },
    ],
  },
  {
    id: "druide",
    role: "HEAL",
    name: "Druide",
    description: "Soigneur de la nature, plus robuste mais moins puissant en soins.",
    strengths: "Très résistant pour un soigneur, bon en solo.",
    weaknesses: "Soins plus faibles que le Prêtre.",
    baseStats: { hp: 85, atk: 4, def: 10, spd: 8 },
    statGrowthPerLevel: { hp: 9, atk: 0.3, def: 1, spd: 0.25 },
    talentTree: [
      {
        id: "druide-racines",
        name: "Racines",
        description: "+ défense par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { def: 1.2 },
      },
      {
        id: "druide-seve-vitale",
        name: "Sève vitale",
        description: "+ vie par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { hp: 7 },
      },
      {
        id: "druide-ecorce",
        name: "Écorce",
        description: "+ défense et + vie par rang, nécessite Racines.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "druide-racines",
        statBonusPerRank: { def: 1.5, hp: 4 },
      },
      {
        id: "druide-renouveau",
        name: "Renouveau",
        description: "+ vie et + dégâts par rang, nécessite Sève vitale.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "druide-seve-vitale",
        statBonusPerRank: { hp: 6, atk: 0.8 },
      },
      {
        id: "druide-coeur-de-la-foret",
        name: "Cœur de la forêt",
        description: "+ défense et + vie, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "druide-ecorce",
        statBonusPerRank: { def: 4, hp: 18 },
      },
      {
        id: "druide-metamorphose",
        name: "Métamorphose",
        description: "+ vie et + dégâts, ultime offensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "druide-renouveau",
        statBonusPerRank: { hp: 12, atk: 3 },
      },
      {
        id: "druide-esprit-ancestral",
        name: "Esprit ancestral",
        description: "+ vie et + défense, nécessite Cœur de la forêt et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "druide-coeur-de-la-foret",
        requiresStarRank: 3,
        statBonusPerRank: { hp: 24, def: 3 },
      },
    ],
  },
  {
    id: "paladin",
    role: "TANK",
    name: "Paladin",
    description: "Protecteur en armure lourde, encaisse pour son groupe.",
    strengths: "Très résistant, absorbe les dégâts.",
    weaknesses: "Dégâts infligés limités.",
    baseStats: { hp: 120, atk: 9, def: 14, spd: 7 },
    statGrowthPerLevel: { hp: 12, atk: 0.8, def: 1.6, spd: 0.2 },
    talentTree: [
      {
        id: "paladin-rempart",
        name: "Rempart",
        description: "+ défense par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { def: 1.5 },
      },
      {
        id: "paladin-endurance",
        name: "Endurance",
        description: "+ vie par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { hp: 10 },
      },
      {
        id: "paladin-vigueur",
        name: "Vigueur",
        description: "+ dégâts par rang, nécessite Rempart.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "paladin-rempart",
        statBonusPerRank: { atk: 1.5 },
      },
      {
        id: "paladin-devouement",
        name: "Dévouement",
        description: "+ vie et + vitesse par rang, nécessite Endurance.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "paladin-endurance",
        statBonusPerRank: { hp: 6, spd: 0.8 },
      },
      {
        id: "paladin-bastion",
        name: "Bastion",
        description: "+ vie et + défense, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "paladin-vigueur",
        statBonusPerRank: { hp: 20, def: 4 },
      },
      {
        id: "paladin-aura-sacree",
        name: "Aura sacrée",
        description: "+ défense et + dégâts, ultime hybride.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "paladin-devouement",
        statBonusPerRank: { def: 3, atk: 3 },
      },
      {
        id: "paladin-jugement",
        name: "Jugement",
        description: "+ défense et + dégâts, nécessite Bastion et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "paladin-bastion",
        requiresStarRank: 3,
        statBonusPerRank: { def: 5, atk: 4 },
      },
    ],
  },
  {
    id: "colosse",
    role: "TANK",
    name: "Colosse",
    description: "Brute massive qui compte sur un réservoir de vie énorme plutôt que sur l'armure.",
    strengths: "Réservoir de vie énorme, frappe plus fort qu'un tank classique.",
    weaknesses: "Moins bonne mitigation, encaisse plus de dégâts bruts par coup.",
    baseStats: { hp: 150, atk: 12, def: 9, spd: 6 },
    statGrowthPerLevel: { hp: 16, atk: 1.2, def: 1, spd: 0.15 },
    talentTree: [
      {
        id: "colosse-muscles-noueux",
        name: "Muscles noueux",
        description: "+ dégâts par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { atk: 1.6 },
      },
      {
        id: "colosse-peau-epaisse",
        name: "Peau épaisse",
        description: "+ vie par rang.",
        tier: 1,
        cost: 1,
        maxRank: 3,
        statBonusPerRank: { hp: 12 },
      },
      {
        id: "colosse-ecrasement",
        name: "Écrasement",
        description: "+ dégâts et + défense par rang, nécessite Muscles noueux.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "colosse-muscles-noueux",
        statBonusPerRank: { atk: 1.8, def: 0.8 },
      },
      {
        id: "colosse-masse-critique",
        name: "Masse critique",
        description: "+ vie et + vitesse par rang, nécessite Peau épaisse.",
        tier: 2,
        cost: 2,
        maxRank: 2,
        requires: "colosse-peau-epaisse",
        statBonusPerRank: { hp: 10, spd: 0.5 },
      },
      {
        id: "colosse-fureur-titanesque",
        name: "Fureur titanesque",
        description: "+ dégâts important, ultime offensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "colosse-ecrasement",
        statBonusPerRank: { atk: 6 },
      },
      {
        id: "colosse-inarretable",
        name: "Inarrêtable",
        description: "+ vie énorme, ultime défensif.",
        tier: 3,
        cost: 3,
        maxRank: 1,
        requires: "colosse-masse-critique",
        statBonusPerRank: { hp: 30 },
      },
      {
        id: "colosse-rage-sans-fin",
        name: "Rage sans fin",
        description: "+ vie et + dégâts, nécessite Inarrêtable et 3★.",
        tier: 4,
        cost: 4,
        maxRank: 1,
        requires: "colosse-inarretable",
        requiresStarRank: 3,
        statBonusPerRank: { hp: 36, atk: 3 },
      },
    ],
  },
];

export function getSubclass(id: string): SubclassDefinition {
  const subclass = SUBCLASSES.find((s) => s.id === id);
  if (!subclass) throw new Error(`Sous-classe inconnue: ${id}`);
  return subclass;
}

export function getSubclassesByRole(role: string): SubclassDefinition[] {
  return SUBCLASSES.filter((s) => s.role === role);
}
