import type { RecipeDefinition } from "@/types/game";

// Single profession to start ("Forgeron"). Add more professions later by
// giving recipes a different `profession` value — the crafting screen groups
// by profession automatically. `tier` sets the rarity odds and affix strength
// of what gets crafted (see lib/game/engine/items.ts CRAFT_RARITY_WEIGHTS);
// `result.statBonus` is the base at "commun", scaled up by the rolled rarity.
export const RECIPES: RecipeDefinition[] = [
  // --- Palier 1 ---
  {
    id: "epee-en-fer",
    name: "Épée en fer",
    profession: "Forgeron",
    description: "Une arme simple mais fiable.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 30, resources: { ore: 6 } },
    result: { name: "Épée en fer", slot: "weapon", statBonus: { atkPhys: 4 } },
  },
  {
    id: "baton-de-frene",
    name: "Bâton de frêne",
    profession: "Forgeron",
    description: "Un bâton souple qui canalise la magie.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 30, resources: { wood: 6 } },
    result: { name: "Bâton de frêne", slot: "weapon", statBonus: { atkMag: 4 } },
  },
  {
    id: "armure-de-cuir-cloutee",
    name: "Armure de cuir cloutée",
    profession: "Forgeron",
    description: "Protection légère renforcée de clous.",
    durationSec: 60 * 3,
    tier: 1,
    cost: { gold: 40, resources: { wood: 4, ore: 4 } },
    result: { name: "Armure de cuir cloutée", slot: "armor", statBonus: { defPhys: 3, hp: 10 } },
  },
  {
    id: "anneau-de-cuivre",
    name: "Anneau de cuivre",
    profession: "Forgeron",
    description: "Un anneau modeste, porte-bonheur des recrues.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 35, resources: { ore: 3, wood: 2 } },
    result: { name: "Anneau de cuivre", slot: "trinket", statBonus: { spd: 1, hp: 8 } },
  },
  {
    id: "arc-court",
    name: "Arc court",
    profession: "Forgeron",
    description: "Un arc léger qui trouve les points faibles.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 35, resources: { wood: 5, ore: 1 } },
    result: { name: "Arc court", slot: "weapon", statBonus: { atkPhys: 3, crit: 2 } },
  },
  {
    id: "dague-affutee",
    name: "Dague affûtée",
    profession: "Forgeron",
    description: "Petite, rapide, et toujours tranchante.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 30, resources: { ore: 5 } },
    result: { name: "Dague affûtée", slot: "weapon", statBonus: { atkPhys: 3, spd: 1 } },
  },
  {
    id: "baguette-d-apprenti",
    name: "Baguette d'apprenti",
    profession: "Forgeron",
    description: "Un bâtonnet gravé qui fait jaillir des étincelles.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 35, resources: { wood: 5, ore: 1 } },
    result: { name: "Baguette d'apprenti", slot: "weapon", statBonus: { atkMag: 3, crit: 2 } },
  },
  {
    id: "tunique-de-lin",
    name: "Tunique de lin",
    profession: "Forgeron",
    description: "Tissu brodé de runes simples contre les sorts.",
    durationSec: 60 * 3,
    tier: 1,
    cost: { gold: 40, resources: { wood: 7 } },
    result: { name: "Tunique de lin", slot: "armor", statBonus: { defMag: 3, hp: 8 } },
  },
  {
    id: "bottes-de-voyage",
    name: "Bottes de voyage",
    profession: "Forgeron",
    description: "On regarde où l'on met les pieds.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 35, resources: { wood: 3, ore: 3 } },
    result: { name: "Bottes de voyage", slot: "trinket", statBonus: { spd: 2, trapRes: 3 } },
  },
  {
    id: "pendentif-de-braise",
    name: "Pendentif de braise",
    profession: "Forgeron",
    description: "Une braise enfermée dans du cuivre, qui boit les flammes.",
    durationSec: 60 * 2,
    tier: 1,
    cost: { gold: 35, resources: { ore: 4, wood: 2 } },
    result: { name: "Pendentif de braise", slot: "trinket", statBonus: { resFeu: 8, hp: 6 } },
  },
  // --- Palier 2 ---
  {
    id: "hache-d-acier",
    name: "Hache d'acier",
    profession: "Forgeron",
    description: "Lourde et tranchante, elle fend boucliers et armures.",
    durationSec: 60 * 5,
    tier: 2,
    cost: { gold: 90, resources: { ore: 14, wood: 6 } },
    result: { name: "Hache d'acier", slot: "weapon", statBonus: { atkPhys: 8 } },
  },
  {
    id: "grimoire-relie",
    name: "Grimoire relié",
    profession: "Forgeron",
    description: "Recueil de formules griffonnées à l'encre d'essence.",
    durationSec: 60 * 5,
    tier: 2,
    cost: { gold: 90, resources: { wood: 10, essence: 4 } },
    result: { name: "Grimoire relié", slot: "weapon", statBonus: { atkMag: 8 } },
  },
  {
    id: "cotte-de-mailles",
    name: "Cotte de mailles",
    profession: "Forgeron",
    description: "Des milliers d'anneaux d'acier entrelacés.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 100, resources: { ore: 16 } },
    result: { name: "Cotte de mailles", slot: "armor", statBonus: { defPhys: 6, hp: 20 } },
  },
  {
    id: "robe-runique",
    name: "Robe runique",
    profession: "Forgeron",
    description: "Tissu brodé de runes qui dévient les sorts.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 100, resources: { wood: 8, essence: 5 } },
    result: { name: "Robe runique", slot: "armor", statBonus: { defMag: 6, hp: 16 } },
  },
  {
    id: "amulette-d-essence",
    name: "Amulette d'essence",
    profession: "Forgeron",
    description: "Amulette imprégnée d'essence magique.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 80, resources: { essence: 5, ore: 2 } },
    result: { name: "Amulette d'essence", slot: "trinket", statBonus: { atkMag: 2, defMag: 2, spd: 2 } },
  },
  {
    id: "arc-long-en-if",
    name: "Arc long en if",
    profession: "Forgeron",
    description: "Une portée redoutable, des flèches qui ne pardonnent pas.",
    durationSec: 60 * 5,
    tier: 2,
    cost: { gold: 90, resources: { wood: 14, ore: 4 } },
    result: { name: "Arc long en if", slot: "weapon", statBonus: { atkPhys: 7, crit: 3 } },
  },
  {
    id: "sceptre-d-orage",
    name: "Sceptre d'orage",
    profession: "Forgeron",
    description: "La foudre crépite au bout du sceptre.",
    durationSec: 60 * 5,
    tier: 2,
    cost: { gold: 95, resources: { wood: 8, essence: 5 } },
    result: { name: "Sceptre d'orage", slot: "weapon", statBonus: { atkMag: 7, critDmg: 10 } },
  },
  {
    id: "brigandine",
    name: "Brigandine",
    profession: "Forgeron",
    description: "Plaques rivetées sous le cuir : contre le fer comme contre la magie.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 100, resources: { ore: 10, wood: 6 } },
    result: { name: "Brigandine", slot: "armor", statBonus: { defPhys: 4, defMag: 3, hp: 14 } },
  },
  {
    id: "cape-du-rodeur",
    name: "Cape du rôdeur",
    profession: "Forgeron",
    description: "Légère et silencieuse, idéale pour traverser les pièges.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 90, resources: { wood: 10, ore: 4 } },
    result: { name: "Cape du rôdeur", slot: "armor", statBonus: { defPhys: 3, spd: 2, trapRes: 6 } },
  },
  {
    id: "anneau-de-givre",
    name: "Anneau de givre",
    profession: "Forgeron",
    description: "Un anneau glacé au toucher, qui repousse le froid.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 85, resources: { essence: 4, ore: 4 } },
    result: { name: "Anneau de givre", slot: "trinket", statBonus: { resGlace: 10, defMag: 2 } },
  },
  {
    id: "talisman-du-demineur",
    name: "Talisman du démineur",
    profession: "Forgeron",
    description: "Il tinte à l'approche d'un mécanisme.",
    durationSec: 60 * 6,
    tier: 2,
    cost: { gold: 85, resources: { ore: 6, essence: 3 } },
    result: { name: "Talisman du démineur", slot: "trinket", statBonus: { trapRes: 8, hp: 10 } },
  },
  // --- Palier 3 ---
  {
    id: "lame-runique",
    name: "Lame runique",
    profession: "Forgeron",
    description: "Acier gravé de runes : frappe aussi bien le corps que l'esprit.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 220, resources: { ore: 22, essence: 10 } },
    result: { name: "Lame runique", slot: "weapon", statBonus: { atkPhys: 9, atkMag: 5 } },
  },
  {
    id: "harnois-du-bastion",
    name: "Harnois du Bastion",
    profession: "Forgeron",
    description: "Armure de plates complète, forgée pour tenir une brèche.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 240, resources: { ore: 24, wood: 10, essence: 6 } },
    result: { name: "Harnois du Bastion", slot: "armor", statBonus: { defPhys: 8, defMag: 5, hp: 35 } },
  },
  {
    id: "talisman-astral",
    name: "Talisman astral",
    profession: "Forgeron",
    description: "Un éclat d'étoile serti d'argent.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 200, resources: { essence: 16, ore: 6 } },
    result: { name: "Talisman astral", slot: "trinket", statBonus: { atkMag: 4, atkPhys: 4, spd: 3 } },
  },
  {
    id: "grand-baton-astral",
    name: "Grand bâton astral",
    profession: "Forgeron",
    description: "Un bâton coiffé d'un éclat du Cœur-d'Étoile.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 230, resources: { wood: 18, essence: 14 } },
    result: { name: "Grand bâton astral", slot: "weapon", statBonus: { atkMag: 13, crit: 3 } },
  },
  {
    id: "espadon-du-titan",
    name: "Espadon du titan",
    profession: "Forgeron",
    description: "Une lame si lourde qu'il faut deux mains et un peu de folie.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 230, resources: { ore: 26, wood: 8 } },
    result: { name: "Espadon du titan", slot: "weapon", statBonus: { atkPhys: 14 } },
  },
  {
    id: "dagues-jumelles",
    name: "Dagues jumelles",
    profession: "Forgeron",
    description: "Deux lames pour frapper deux fois là où ça fait mal.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 220, resources: { ore: 16, essence: 8 } },
    result: { name: "Dagues jumelles", slot: "weapon", statBonus: { atkPhys: 9, crit: 5, critDmg: 10 } },
  },
  {
    id: "manteau-des-arcanes",
    name: "Manteau des arcanes",
    profession: "Forgeron",
    description: "Un manteau tissé de fils d'essence.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 220, resources: { wood: 12, essence: 14 } },
    result: { name: "Manteau des arcanes", slot: "armor", statBonus: { defMag: 9, atkMag: 2, hp: 28 } },
  },
  {
    id: "egide-sacree",
    name: "Égide sacrée",
    profession: "Forgeron",
    description: "Bénie contre la lumière comme contre les ombres.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 250, resources: { ore: 18, essence: 10 } },
    result: { name: "Égide sacrée", slot: "armor", statBonus: { defPhys: 6, defMag: 6, resSacre: 8, resOmbre: 8, hp: 25 } },
  },
  {
    id: "prisme-elementaire",
    name: "Prisme élémentaire",
    profession: "Forgeron",
    description: "Un cristal qui disperse feu, glace, foudre, lumière et ombre.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 210, resources: { essence: 18, ore: 6 } },
    result: { name: "Prisme élémentaire", slot: "trinket", statBonus: { resFeu: 6, resGlace: 6, resFoudre: 6, resSacre: 6, resOmbre: 6 } },
  },
  {
    id: "oeil-du-bourreau",
    name: "Œil du bourreau",
    profession: "Forgeron",
    description: "Une gemme qui voit toujours le point faible.",
    durationSec: 60 * 10,
    tier: 3,
    cost: { gold: 220, resources: { essence: 14, ore: 8 } },
    result: { name: "Œil du bourreau", slot: "trinket", statBonus: { crit: 5, critDmg: 20 } },
  },
];

export function getRecipe(id: string): RecipeDefinition {
  const recipe = RECIPES.find((r) => r.id === id);
  if (!recipe) throw new Error(`Recette inconnue: ${id}`);
  return recipe;
}
