import type { SpellDefinition } from "@/types/game";

// 5 attack spells per class (40) + 6 raid utility spells (disarm/scout). Every spell has TWO distinct combat
// effects — never a passive stat bonus: a raidEffectTag that modifies its
// owner's attack in turn-based dungeon-raid combat (lib/game/engine/dungeonCombat.ts),
// and an arenaAbilityTag that modifies its owner's contribution to the
// real-time arena mini-game (lib/game/arena/engine.ts). Owned via gacha
// (UserProfile.componentRanks) before they can be equipped; duplicates raise
// their rank instead of granting a second copy — rank currently only affects
// arena magnitude (per-count scaling already there); raid effects are flat.
// `element` (optional) is the spell's damage element: the hero's first equipped
// elemental spell sets the element of ALL its attacks, in both modes.
export const SPELLS: SpellDefinition[] = [
  // --- Guerrier ---
  {
    id: "spell-frappe-de-zone",
    classId: "guerrier",
    name: "Frappe de zone",
    description: "Chaque coup touche aussi un ennemi proche en éclaboussure.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "cleave",
    element: "feu",
  },
  {
    id: "spell-coup-fulgurant",
    classId: "guerrier",
    name: "Coup fulgurant",
    description: "Frappe avec une force redoublée les ennemis déjà affaiblis.",
    raidEffectTag: "execute",
    arenaAbilityTag: "execute",
    element: "foudre",
  },
  {
    id: "spell-posture-offensive",
    classId: "guerrier",
    name: "Posture offensive",
    description: "Un assaut qui ignore une partie de la garde adverse.",
    raidEffectTag: "pierce",
    arenaAbilityTag: "dmgbuff",
  },
  {
    id: "spell-endurance-martiale",
    classId: "guerrier",
    name: "Endurance martiale",
    description: "Se protège juste avant de porter le coup.",
    raidEffectTag: "shield",
    arenaAbilityTag: "haste",
  },
  {
    id: "spell-cri-de-guerre",
    classId: "guerrier",
    name: "Cri de guerre",
    description: "Un cri percutant qui assomme la cible.",
    raidEffectTag: "stun",
    arenaAbilityTag: "cleave",
    element: "foudre",
  },
  // --- Archer ---
  {
    id: "spell-tir-multiple",
    classId: "archer",
    name: "Tir multiple",
    description: "Décoche un projectile supplémentaire à chaque tir.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "multishot",
  },
  {
    id: "spell-oeil-percant",
    classId: "archer",
    name: "Œil perçant",
    description: "Vise la moindre faiblesse pour achever les blessés.",
    raidEffectTag: "execute",
    arenaAbilityTag: "execute",
    element: "glace",
  },
  {
    id: "spell-tir-a-bout-portant",
    classId: "archer",
    name: "Tir à bout portant",
    description: "Un tir qui traverse les défenses de plein fouet.",
    raidEffectTag: "pierce",
    arenaAbilityTag: "chain",
    element: "foudre",
  },
  {
    id: "spell-retraite-agile",
    classId: "archer",
    name: "Retraite agile",
    description: "Recule juste après avoir tiré, hors de portée des ripostes.",
    raidEffectTag: "shield",
    arenaAbilityTag: "haste",
  },
  {
    id: "spell-volee-empoisonnee",
    classId: "archer",
    name: "Volée empoisonnée",
    description: "Chaque flèche empoisonne un peu plus la plaie.",
    raidEffectTag: "poison",
    arenaAbilityTag: "venom",
    element: "ombre",
  },
  // --- Prêtre ---
  {
    id: "spell-lumiere-curative",
    classId: "pretre",
    name: "Lumière curative",
    description: "Un soin renforcé sur l'allié le plus faible, au lieu d'attaquer.",
    raidEffectTag: "heal",
    arenaAbilityTag: "regen",
    element: "sacre",
  },
  {
    id: "spell-benediction",
    classId: "pretre",
    name: "Bénédiction",
    description: "Un halo protecteur juste avant l'impact.",
    raidEffectTag: "shield",
    arenaAbilityTag: "dmgbuff",
    element: "sacre",
  },
  {
    id: "spell-chatiment-sacre",
    classId: "pretre",
    name: "Châtiment sacré",
    description: "Une lumière implacable qui achève les affaiblis.",
    raidEffectTag: "execute",
    arenaAbilityTag: "meteor",
    element: "sacre",
  },
  {
    id: "spell-aura-apaisante",
    classId: "pretre",
    name: "Aura apaisante",
    description: "Un soin renforcé sur l'allié le plus faible, au lieu d'attaquer.",
    raidEffectTag: "heal",
    arenaAbilityTag: "regen",
  },
  {
    id: "spell-zele-devot",
    classId: "pretre",
    name: "Zèle dévot",
    description: "La ferveur étourdit la cible frappée.",
    raidEffectTag: "stun",
    arenaAbilityTag: "dmgbuff",
    element: "sacre",
  },
  // --- Druide ---
  {
    id: "spell-instinct-sauvage",
    classId: "druide",
    name: "Instinct sauvage",
    description: "Griffe la cible principale et une proche en éclaboussure.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "haste",
  },
  {
    id: "spell-griffe-naturelle",
    classId: "druide",
    name: "Griffe naturelle",
    description: "Une morsure qui infecte durablement la plaie.",
    raidEffectTag: "poison",
    arenaAbilityTag: "venom",
    element: "ombre",
  },
  {
    id: "spell-racines-epaisses",
    classId: "druide",
    name: "Racines épaisses",
    description: "Emprisonne la cible frappée dans les racines.",
    raidEffectTag: "stun",
    arenaAbilityTag: "nova",
    element: "glace",
  },
  {
    id: "spell-metamorphose-bestiale",
    classId: "druide",
    name: "Métamorphose bestiale",
    description: "La forme animale fond sur les proies affaiblies.",
    raidEffectTag: "execute",
    arenaAbilityTag: "lifesteal",
    element: "foudre",
  },
  {
    id: "spell-souffle-vital",
    classId: "druide",
    name: "Souffle vital",
    description: "Un soin renforcé sur l'allié le plus faible, au lieu d'attaquer.",
    raidEffectTag: "heal",
    arenaAbilityTag: "regen",
  },
  // --- Paladin ---
  {
    id: "spell-benediction-du-rempart",
    classId: "paladin",
    name: "Bénédiction du rempart",
    description: "Une garde solide qui absorbe le prochain coup reçu.",
    raidEffectTag: "shield",
    arenaAbilityTag: "barrier",
    element: "sacre",
  },
  {
    id: "spell-jugement",
    classId: "paladin",
    name: "Jugement",
    description: "Juge et châtie sans pitié les ennemis affaiblis.",
    raidEffectTag: "execute",
    arenaAbilityTag: "meteor",
    element: "sacre",
  },
  {
    id: "spell-bouclier-sacre",
    classId: "paladin",
    name: "Bouclier sacré",
    description: "Se protège avant l'assaut suivant.",
    raidEffectTag: "shield",
    arenaAbilityTag: "barrier",
    element: "sacre",
  },
  {
    id: "spell-charge-heroique",
    classId: "paladin",
    name: "Charge héroïque",
    description: "Fonce dans la mêlée, frappant large.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "cleave",
    element: "feu",
  },
  {
    id: "spell-serment-inebranlable",
    classId: "paladin",
    name: "Serment inébranlable",
    description: "Une détermination qui impose le silence à la cible.",
    raidEffectTag: "stun",
    arenaAbilityTag: "dmgbuff",
  },
  // --- Colosse ---
  {
    id: "spell-morsure-vampirique",
    classId: "colosse",
    name: "Morsure vampirique",
    description: "Convertit une partie des dégâts infligés en vie.",
    raidEffectTag: "lifesteal",
    arenaAbilityTag: "lifesteal",
    element: "ombre",
  },
  {
    id: "spell-ecrasement",
    classId: "colosse",
    name: "Écrasement",
    description: "Un coup massif qui écrase les défenses adverses.",
    raidEffectTag: "pierce",
    arenaAbilityTag: "meteor",
  },
  {
    id: "spell-peau-de-fer",
    classId: "colosse",
    name: "Peau de fer",
    description: "Encaisse avant de rendre le coup.",
    raidEffectTag: "shield",
    arenaAbilityTag: "barrier",
  },
  {
    id: "spell-fureur-titanesque",
    classId: "colosse",
    name: "Fureur titanesque",
    description: "La rage s'acharne sur les cibles les plus faibles.",
    raidEffectTag: "execute",
    arenaAbilityTag: "execute",
    element: "feu",
  },
  {
    id: "spell-poigne-implacable",
    classId: "colosse",
    name: "Poigne implacable",
    description: "Une prise brutale qui immobilise l'adversaire.",
    raidEffectTag: "stun",
    arenaAbilityTag: "cleave",
  },
  // --- Mage ---
  {
    id: "spell-boule-de-feu",
    classId: "mage",
    name: "Boule de feu",
    description: "Une explosion de flammes qui lèche aussi les ennemis voisins.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "meteor",
    element: "feu",
  },
  {
    id: "spell-javelot-de-glace",
    classId: "mage",
    name: "Javelot de glace",
    description: "Un trait de givre qui fige la cible sur place.",
    raidEffectTag: "stun",
    arenaAbilityTag: "nova",
    element: "glace",
  },
  {
    id: "spell-chaine-d-eclairs",
    classId: "mage",
    name: "Chaîne d'éclairs",
    description: "La foudre rebondit d'une cible à l'autre.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "chain",
    element: "foudre",
  },
  {
    id: "spell-brulure-arcanique",
    classId: "mage",
    name: "Brûlure arcanique",
    description: "Des flammes qui continuent de ronger la cible.",
    raidEffectTag: "poison",
    arenaAbilityTag: "venom",
    element: "feu",
  },
  {
    id: "spell-armure-de-givre",
    classId: "mage",
    name: "Armure de givre",
    description: "Une gangue de glace qui amortit le prochain coup.",
    raidEffectTag: "shield",
    arenaAbilityTag: "nova",
    element: "glace",
  },
  // --- Assassin ---
  {
    id: "spell-lame-empoisonnee",
    classId: "assassin",
    name: "Lame empoisonnée",
    description: "Un venin d'ombre qui nourrit son porteur.",
    raidEffectTag: "poison",
    arenaAbilityTag: "venom",
    element: "ombre",
  },
  {
    id: "spell-pas-de-l-ombre",
    classId: "assassin",
    name: "Pas de l'ombre",
    description: "Disparaît dans les ténèbres avant de frapper.",
    raidEffectTag: "shield",
    arenaAbilityTag: "haste",
    element: "ombre",
  },
  {
    id: "spell-frappe-mortelle",
    classId: "assassin",
    name: "Frappe mortelle",
    description: "Achève sans hésiter une cible à bout de souffle.",
    raidEffectTag: "execute",
    arenaAbilityTag: "execute",
    element: "ombre",
  },
  {
    id: "spell-eventail-de-dagues",
    classId: "assassin",
    name: "Éventail de dagues",
    description: "Une gerbe de lames qui touche plusieurs ennemis.",
    raidEffectTag: "cleave",
    arenaAbilityTag: "multishot",
  },
  {
    id: "spell-coup-bas",
    classId: "assassin",
    name: "Coup bas",
    description: "Un coup vicieux qui laisse la cible sonnée.",
    raidEffectTag: "stun",
    arenaAbilityTag: "lifesteal",
  },
  // --- Utilitaires de raid (Désamorçage / Éclaireur) : pas d'effet de combat en donjon, mais un
  // atout d'équipe. Leur classe est celle qui les maîtrise le mieux. ---
  {
    id: "spell-desamorcage",
    classId: "assassin",
    name: "Désamorçage",
    description: "Repère et neutralise les mécanismes avant qu'ils ne se déclenchent.",
    raidEffectTag: "disarm",
    arenaAbilityTag: "haste",
  },
  {
    id: "spell-pas-de-loup",
    classId: "archer",
    name: "Pas de loup",
    description: "Guide l'équipe sur les dalles sûres.",
    raidEffectTag: "disarm",
    arenaAbilityTag: "multishot",
  },
  {
    id: "spell-garde-runique",
    classId: "paladin",
    name: "Garde runique",
    description: "Un bouclier de runes qui absorbe les pièges magiques.",
    raidEffectTag: "disarm",
    arenaAbilityTag: "barrier",
    element: "sacre",
  },
  {
    id: "spell-oeil-de-l-eclaireur",
    classId: "archer",
    name: "Œil de l'éclaireur",
    description: "Scrute les salles voisines avant d'y entrer.",
    raidEffectTag: "scout",
    arenaAbilityTag: "multishot",
  },
  {
    id: "spell-murmure-des-racines",
    classId: "druide",
    name: "Murmure des racines",
    description: "Les racines racontent ce qui se cache derrière les murs.",
    raidEffectTag: "scout",
    arenaAbilityTag: "regen",
  },
  {
    id: "spell-oeil-arcanique",
    classId: "mage",
    name: "Œil arcanique",
    description: "Un œil flottant qui explore en avance.",
    raidEffectTag: "scout",
    arenaAbilityTag: "chain",
    element: "foudre",
  },
];

export function getSpell(id: string): SpellDefinition {
  const spell = SPELLS.find((s) => s.id === id);
  if (!spell) throw new Error(`Sort inconnu: ${id}`);
  return spell;
}

export function tryGetSpell(id: string): SpellDefinition | undefined {
  return SPELLS.find((s) => s.id === id);
}

export function getSpellsForClass(classId: string | undefined): SpellDefinition[] {
  return SPELLS.filter((s) => !s.classId || s.classId === classId);
}
