import type { TalentNode } from "@/types/game";

// Flat catalog of every class's talent tree (7 nodes/class: 2 tier-1, 2 tier-2,
// 2 tier-3 ultimates, 1 tier-4 capstone). A node must be owned (gacha-unlocked,
// tracked by rank in UserProfile.componentRanks) before points can be spent into
// it — see app/api/heroes/[id]/talents/route.ts. Physical classes (guerrier,
// archer, paladin, colosse) scale atkPhys/defPhys; magical ones (pretre, druide)
// scale atkMag/defMag. Mage and Assassin also lean on crit/critDmg, and a few
// defensive ultimates grant elemental resistances.
export const TALENTS: TalentNode[] = [
  // --- Guerrier (physique) ---
  {
    id: "guerrier-force-brute",
    classId: "guerrier",
    name: "Force brute",
    description: "+ dégâts physiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { atkPhys: 1.5 },
  },
  {
    id: "guerrier-cuir-durci",
    classId: "guerrier",
    name: "Cuir durci",
    description: "+ défense physique par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { defPhys: 1 },
  },
  {
    id: "guerrier-fureur",
    classId: "guerrier",
    name: "Fureur",
    description: "+ vitesse par rang, nécessite Force brute.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "guerrier-force-brute",
    statBonusPerRank: { spd: 1, atkPhys: 1 },
  },
  {
    id: "guerrier-parade",
    classId: "guerrier",
    name: "Parade",
    description: "+ défense physique et + vie par rang, nécessite Cuir durci.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "guerrier-cuir-durci",
    statBonusPerRank: { defPhys: 1, hp: 4 },
  },
  {
    id: "guerrier-acharnement",
    classId: "guerrier",
    name: "Acharnement",
    description: "+ dégâts physiques et + vie par rang, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "guerrier-fureur",
    statBonusPerRank: { atkPhys: 4, hp: 10 },
  },
  {
    id: "guerrier-titan",
    classId: "guerrier",
    name: "Titan",
    description: "+ défense physique et + vie par rang, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "guerrier-parade",
    statBonusPerRank: { defPhys: 4, hp: 16 },
  },
  {
    id: "guerrier-legende",
    classId: "guerrier",
    name: "Légende vivante",
    description: "+ dégâts physiques et + vie, nécessite Acharnement et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "guerrier-acharnement",
    requiresStarRank: 3,
    statBonusPerRank: { atkPhys: 6, hp: 14 },
  },
  // --- Archer (physique) ---
  {
    id: "archer-oeil-de-faucon",
    classId: "archer",
    name: "Œil de faucon",
    description: "+ dégâts physiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { atkPhys: 1.3 },
  },
  {
    id: "archer-pas-legers",
    classId: "archer",
    name: "Pas légers",
    description: "+ vitesse par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { spd: 1.2 },
  },
  {
    id: "archer-tir-rapide",
    classId: "archer",
    name: "Tir rapide",
    description: "+ dégâts physiques et + vitesse par rang, nécessite Œil de faucon.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "archer-oeil-de-faucon",
    statBonusPerRank: { atkPhys: 1.5, spd: 0.5 },
  },
  {
    id: "archer-esquive",
    classId: "archer",
    name: "Esquive",
    description: "+ vitesse, + défense physique et + résistance aux pièges par rang, nécessite Pas légers.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "archer-pas-legers",
    statBonusPerRank: { spd: 1, defPhys: 1, trapRes: 6 },
  },
  {
    id: "archer-pluie-de-fleches",
    classId: "archer",
    name: "Pluie de flèches",
    description: "+ dégâts physiques important, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "archer-tir-rapide",
    statBonusPerRank: { atkPhys: 6 },
  },
  {
    id: "archer-ombre-furtive",
    classId: "archer",
    name: "Ombre furtive",
    description: "+ vitesse et + vie, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "archer-esquive",
    statBonusPerRank: { spd: 3, hp: 12 },
  },
  {
    id: "archer-tempete-de-fleches",
    classId: "archer",
    name: "Tempête de flèches",
    description: "+ dégâts physiques et + vitesse, nécessite Pluie de flèches et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "archer-pluie-de-fleches",
    requiresStarRank: 3,
    statBonusPerRank: { atkPhys: 7, spd: 2 },
  },
  // --- Prêtre (magique) ---
  {
    id: "pretre-lumiere-apaisante",
    classId: "pretre",
    name: "Lumière apaisante",
    description: "+ vie max par rang (soins plus efficaces en valeur).",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { hp: 6 },
  },
  {
    id: "pretre-devotion",
    classId: "pretre",
    name: "Dévotion",
    description: "+ défense magique par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { defMag: 1 },
  },
  {
    id: "pretre-zele",
    classId: "pretre",
    name: "Zèle",
    description: "+ vitesse par rang, nécessite Lumière apaisante.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "pretre-lumiere-apaisante",
    statBonusPerRank: { spd: 1 },
  },
  {
    id: "pretre-foi-ardente",
    classId: "pretre",
    name: "Foi ardente",
    description: "+ dégâts magiques et + défense magique par rang, nécessite Dévotion.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "pretre-devotion",
    statBonusPerRank: { atkMag: 1, defMag: 1 },
  },
  {
    id: "pretre-sanctuaire",
    classId: "pretre",
    name: "Sanctuaire",
    description: "+ vie et + défense magique, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "pretre-zele",
    statBonusPerRank: { hp: 15, defMag: 3 },
  },
  {
    id: "pretre-martyr",
    classId: "pretre",
    name: "Martyr",
    description: "+ vie et + dégâts magiques, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "pretre-foi-ardente",
    statBonusPerRank: { hp: 10, atkMag: 4 },
  },
  {
    id: "pretre-benediction-divine",
    classId: "pretre",
    name: "Bénédiction divine",
    description: "+ vie et + défense magique, nécessite Sanctuaire et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "pretre-sanctuaire",
    requiresStarRank: 3,
    statBonusPerRank: { hp: 20, defMag: 4 },
  },
  // --- Druide (magique) ---
  {
    id: "druide-racines",
    classId: "druide",
    name: "Racines",
    description: "+ défense magique par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { defMag: 1.2 },
  },
  {
    id: "druide-seve-vitale",
    classId: "druide",
    name: "Sève vitale",
    description: "+ vie par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { hp: 7 },
  },
  {
    id: "druide-ecorce",
    classId: "druide",
    name: "Écorce",
    description: "+ défense magique et + vie par rang, nécessite Racines.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "druide-racines",
    statBonusPerRank: { defMag: 1.5, hp: 4 },
  },
  {
    id: "druide-renouveau",
    classId: "druide",
    name: "Renouveau",
    description: "+ vie et + dégâts magiques par rang, nécessite Sève vitale.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "druide-seve-vitale",
    statBonusPerRank: { hp: 6, atkMag: 0.8 },
  },
  {
    id: "druide-coeur-de-la-foret",
    classId: "druide",
    name: "Cœur de la forêt",
    description: "+ défense magique et + vie, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "druide-ecorce",
    statBonusPerRank: { defMag: 4, hp: 18 },
  },
  {
    id: "druide-metamorphose",
    classId: "druide",
    name: "Métamorphose",
    description: "+ vie et + dégâts magiques, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "druide-renouveau",
    statBonusPerRank: { hp: 12, atkMag: 3 },
  },
  {
    id: "druide-esprit-ancestral",
    classId: "druide",
    name: "Esprit ancestral",
    description: "+ vie et + défense magique, nécessite Cœur de la forêt et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "druide-coeur-de-la-foret",
    requiresStarRank: 3,
    statBonusPerRank: { hp: 24, defMag: 3 },
  },
  // --- Paladin (physique) ---
  {
    id: "paladin-rempart",
    classId: "paladin",
    name: "Rempart",
    description: "+ défense physique par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { defPhys: 1.5 },
  },
  {
    id: "paladin-endurance",
    classId: "paladin",
    name: "Endurance",
    description: "+ vie par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { hp: 10 },
  },
  {
    id: "paladin-vigueur",
    classId: "paladin",
    name: "Vigueur",
    description: "+ dégâts physiques par rang, nécessite Rempart.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "paladin-rempart",
    statBonusPerRank: { atkPhys: 1.5 },
  },
  {
    id: "paladin-devouement",
    classId: "paladin",
    name: "Dévouement",
    description: "+ vie et + vitesse par rang, nécessite Endurance.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "paladin-endurance",
    statBonusPerRank: { hp: 6, spd: 0.8 },
  },
  {
    id: "paladin-bastion",
    classId: "paladin",
    name: "Bastion",
    description: "+ vie et + défense physique, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "paladin-vigueur",
    statBonusPerRank: { hp: 20, defPhys: 4 },
  },
  {
    id: "paladin-aura-sacree",
    classId: "paladin",
    name: "Aura sacrée",
    description: "+ défense physique et + dégâts physiques, ultime hybride.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "paladin-devouement",
    statBonusPerRank: { defPhys: 3, atkPhys: 3 },
  },
  {
    id: "paladin-jugement",
    classId: "paladin",
    name: "Jugement",
    description: "+ défense physique et + dégâts physiques, nécessite Bastion et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "paladin-bastion",
    requiresStarRank: 3,
    statBonusPerRank: { defPhys: 5, atkPhys: 4 },
  },
  // --- Colosse (physique) ---
  {
    id: "colosse-muscles-noueux",
    classId: "colosse",
    name: "Muscles noueux",
    description: "+ dégâts physiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { atkPhys: 1.6 },
  },
  {
    id: "colosse-peau-epaisse",
    classId: "colosse",
    name: "Peau épaisse",
    description: "+ vie par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { hp: 12 },
  },
  {
    id: "colosse-ecrasement",
    classId: "colosse",
    name: "Écrasement",
    description: "+ dégâts physiques et + défense physique par rang, nécessite Muscles noueux.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "colosse-muscles-noueux",
    statBonusPerRank: { atkPhys: 1.8, defPhys: 0.8 },
  },
  {
    id: "colosse-masse-critique",
    classId: "colosse",
    name: "Masse critique",
    description: "+ vie et + vitesse par rang, nécessite Peau épaisse.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "colosse-peau-epaisse",
    statBonusPerRank: { hp: 10, spd: 0.5 },
  },
  {
    id: "colosse-fureur-titanesque",
    classId: "colosse",
    name: "Fureur titanesque",
    description: "+ dégâts physiques important, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "colosse-ecrasement",
    statBonusPerRank: { atkPhys: 6 },
  },
  {
    id: "colosse-inarretable",
    classId: "colosse",
    name: "Inarrêtable",
    description: "+ vie énorme, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "colosse-masse-critique",
    statBonusPerRank: { hp: 30 },
  },
  {
    id: "colosse-rage-sans-fin",
    classId: "colosse",
    name: "Rage sans fin",
    description: "+ vie et + dégâts physiques, nécessite Inarrêtable et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "colosse-inarretable",
    requiresStarRank: 3,
    statBonusPerRank: { hp: 36, atkPhys: 3 },
  },
  // --- Mage (magique, critiques) ---
  {
    id: "mage-savoir-arcanique",
    classId: "mage",
    name: "Savoir arcanique",
    description: "+ dégâts magiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { atkMag: 1.6 },
  },
  {
    id: "mage-concentration",
    classId: "mage",
    name: "Concentration",
    description: "+ chances de coup critique par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { crit: 2 },
  },
  {
    id: "mage-surtension",
    classId: "mage",
    name: "Surtension",
    description: "+ dégâts magiques et + dégâts critiques par rang, nécessite Savoir arcanique.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "mage-savoir-arcanique",
    statBonusPerRank: { atkMag: 1.2, critDmg: 8 },
  },
  {
    id: "mage-bouclier-de-mana",
    classId: "mage",
    name: "Bouclier de mana",
    description: "+ défense magique et + vie par rang, nécessite Concentration.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "mage-concentration",
    statBonusPerRank: { defMag: 1.5, hp: 5 },
  },
  {
    id: "mage-cataclysme",
    classId: "mage",
    name: "Cataclysme",
    description: "+ dégâts magiques important, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "mage-surtension",
    statBonusPerRank: { atkMag: 6, critDmg: 10 },
  },
  {
    id: "mage-barriere-elementaire",
    classId: "mage",
    name: "Barrière élémentaire",
    description: "+ résistances au feu, à la glace et à la foudre, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "mage-bouclier-de-mana",
    statBonusPerRank: { resFeu: 12, resGlace: 12, resFoudre: 12, hp: 10 },
  },
  {
    id: "mage-archimage",
    classId: "mage",
    name: "Archimage",
    description: "+ dégâts magiques et + critiques, nécessite Cataclysme et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "mage-cataclysme",
    requiresStarRank: 3,
    statBonusPerRank: { atkMag: 7, crit: 5 },
  },
  // --- Assassin (physique, critiques) ---
  {
    id: "assassin-lames-affutees",
    classId: "assassin",
    name: "Lames affûtées",
    description: "+ dégâts physiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { atkPhys: 1.3 },
  },
  {
    id: "assassin-sang-froid",
    classId: "assassin",
    name: "Sang-froid",
    description: "+ dégâts critiques par rang.",
    tier: 1,
    cost: 1,
    maxRank: 3,
    statBonusPerRank: { critDmg: 6 },
  },
  {
    id: "assassin-point-faible",
    classId: "assassin",
    name: "Point faible",
    description: "+ chances de coup critique par rang, nécessite Lames affûtées.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "assassin-lames-affutees",
    statBonusPerRank: { crit: 3, atkPhys: 0.5 },
  },
  {
    id: "assassin-evasion",
    classId: "assassin",
    name: "Évasion",
    description: "+ vitesse, + résistance à l'ombre et aux pièges par rang, nécessite Sang-froid.",
    tier: 2,
    cost: 2,
    maxRank: 2,
    requires: "assassin-sang-froid",
    statBonusPerRank: { spd: 1, resOmbre: 6, trapRes: 8 },
  },
  {
    id: "assassin-execution",
    classId: "assassin",
    name: "Exécution",
    description: "+ dégâts critiques important, ultime offensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "assassin-point-faible",
    statBonusPerRank: { critDmg: 25, atkPhys: 3 },
  },
  {
    id: "assassin-voile-nocturne",
    classId: "assassin",
    name: "Voile nocturne",
    description: "+ vie, + défenses et + résistance à l'ombre, ultime défensif.",
    tier: 3,
    cost: 3,
    maxRank: 1,
    requires: "assassin-evasion",
    statBonusPerRank: { hp: 16, defPhys: 2, defMag: 2, resOmbre: 10 },
  },
  {
    id: "assassin-maitre-des-ombres",
    classId: "assassin",
    name: "Maître des ombres",
    description: "+ critiques et + dégâts physiques, nécessite Exécution et 3★.",
    tier: 4,
    cost: 4,
    maxRank: 1,
    requires: "assassin-execution",
    requiresStarRank: 3,
    statBonusPerRank: { crit: 6, critDmg: 15, atkPhys: 3 },
  },
];

export function getTalent(id: string): TalentNode {
  const node = TALENTS.find((t) => t.id === id);
  if (!node) throw new Error(`Talent inconnu: ${id}`);
  return node;
}

export function getTalentsForClass(classId: string): TalentNode[] {
  return TALENTS.filter((t) => t.classId === classId);
}
