import type { TavernNpc } from "@/types/game";

// Tavern visitors. One of them sits at the counter per 30-min window (see lib/game/tavern.ts).
// - marchand: offers bought with gold/resources, each once per visit.
// - conteur: a story (optionally with an offer at the end).
// - bienfaiteur: free gifts; with offerMode "pickOne" the player picks one of them.
// - parieur: bets — the cost is always paid, the reward only on a win (`winChance`).
// Offer ids only need to be unique within their NPC. Never hand out classes/spells/talents
// here: those stay gacha-earned.
export const TAVERN_NPCS: TavernNpc[] = [
  // ─────────────────────────── Marchands ───────────────────────────
  {
    id: "brunhilde-quincaillere",
    name: "Brunhilde",
    title: "Quincaillière ambulante",
    portrait: "🧺",
    kind: "marchand",
    rarity: "commun",
    greeting: "Clous, cordes, lingots… tout ce qu'il faut pour réparer ce que les monstres cassent !",
    offers: [
      { id: "minerai", label: "Sac de minerai", cost: { gold: 60 }, reward: { resources: { ore: 10 } } },
      { id: "bois", label: "Fagot de bois sec", cost: { gold: 60 }, reward: { resources: { wood: 10 } } },
      { id: "epee", label: "Épée en fer d'occasion", cost: { gold: 45 }, reward: { item: { recipeId: "epee-en-fer" } } },
    ],
  },
  {
    id: "orvald-bucheron",
    name: "Orvald",
    title: "Bûcheron de la Lisière",
    portrait: "🪓",
    kind: "marchand",
    rarity: "commun",
    greeting: "La forêt donne, la forêt reprend. Aujourd'hui elle donne — profitez-en.",
    offers: [
      { id: "bois-gros", label: "Charrette de bois", cost: { gold: 140 }, reward: { resources: { wood: 25 } } },
      { id: "baton", label: "Bâton de frêne taillé main", cost: { gold: 40, resources: { wood: 2 } }, reward: { item: { recipeId: "baton-de-frene" } } },
    ],
  },
  {
    id: "gorm-mineur",
    name: "Gorm Barbe-de-Suie",
    title: "Mineur nain",
    portrait: "⛏️",
    kind: "marchand",
    rarity: "commun",
    greeting: "J'ai remonté ça des Mines abandonnées. Ne demandez pas ce qui me poursuivait.",
    offers: [
      { id: "minerai-gros", label: "Wagonnet de minerai", cost: { gold: 140 }, reward: { resources: { ore: 25 } } },
      { id: "troc", label: "Troquer du bois contre du minerai", cost: { resources: { wood: 15 } }, reward: { resources: { ore: 12 } } },
    ],
  },
  {
    id: "selene-alchimiste",
    name: "Sélène",
    title: "Alchimiste itinérante",
    portrait: "⚗️",
    kind: "marchand",
    rarity: "commun",
    greeting: "L'essence, c'est de la magie en bouteille. Et la magie, ça se paie.",
    offers: [
      { id: "essence", label: "Fiole d'essence", cost: { gold: 90 }, reward: { resources: { essence: 8 } } },
      { id: "distiller", label: "Distiller du bois en essence", cost: { resources: { wood: 20 } }, reward: { resources: { essence: 6 } } },
      { id: "amulette", label: "Amulette d'essence", cost: { gold: 110, resources: { essence: 4 } }, reward: { item: { recipeId: "amulette-d-essence" } } },
    ],
  },
  {
    id: "pip-colporteur",
    name: "Pip",
    title: "Colporteur halfelin",
    portrait: "🎒",
    kind: "marchand",
    rarity: "commun",
    greeting: "Tout à petit prix ! Enfin, petit… pour un halfelin.",
    offers: [
      { id: "anneau", label: "Anneau de cuivre", cost: { gold: 40 }, reward: { item: { recipeId: "anneau-de-cuivre" } } },
      { id: "armure", label: "Armure de cuir cloutée", cost: { gold: 50 }, reward: { item: { recipeId: "armure-de-cuir-cloutee" } } },
      { id: "lot", label: "Lot mystère de ressources", cost: { gold: 80 }, reward: { resources: { wood: 5, ore: 5, essence: 2 } } },
    ],
  },
  {
    id: "hector-ferrailleur",
    name: "Hector",
    title: "Ferrailleur",
    portrait: "🔩",
    kind: "marchand",
    rarity: "commun",
    greeting: "Vos vieilles lames, je les fonds. Vos éclats, je les rachète. Enfin, je les vends.",
    offers: [
      { id: "eclats", label: "Poignée d'éclats de forge", cost: { gold: 100 }, reward: { forgeShards: 8 } },
      { id: "eclats-minerai", label: "Éclats contre minerai", cost: { resources: { ore: 12 } }, reward: { forgeShards: 6 } },
    ],
  },
  {
    id: "mirela-changeuse",
    name: "Mirela",
    title: "Changeuse de monnaie",
    portrait: "⚖️",
    kind: "marchand",
    rarity: "rare",
    greeting: "Or contre cristaux, cristaux contre or. Ma commission ? Un sourire. Et un peu d'or.",
    offers: [
      { id: "cristal", label: "Un cristal d'invocation", cost: { gold: 300 }, reward: { crystals: 1 } },
      { id: "cristaux", label: "Trois cristaux d'invocation", cost: { gold: 800 }, reward: { crystals: 3 } },
    ],
  },
  {
    id: "tobias-armurier",
    name: "Tobias",
    title: "Armurier de la garde",
    portrait: "🛡️",
    kind: "marchand",
    rarity: "commun",
    greeting: "Surplus de l'armurerie. Personne ne remarquera qu'il en manque.",
    offers: [
      { id: "cotte", label: "Cotte de mailles", cost: { gold: 160, resources: { ore: 6 } }, reward: { item: { recipeId: "cotte-de-mailles" } } },
      { id: "hache", label: "Hache d'acier", cost: { gold: 160, resources: { ore: 6 } }, reward: { item: { recipeId: "hache-d-acier" } } },
    ],
  },
  {
    id: "ysolde-libraire",
    name: "Ysolde",
    title: "Libraire des arcanes",
    portrait: "📚",
    kind: "marchand",
    rarity: "commun",
    greeting: "Chaque grimoire a un propriétaire. Parfois, il est même encore vivant.",
    offers: [
      { id: "grimoire", label: "Grimoire relié", cost: { gold: 160, resources: { essence: 4 } }, reward: { item: { recipeId: "grimoire-relie" } } },
      { id: "robe", label: "Robe runique", cost: { gold: 160, resources: { essence: 4 } }, reward: { item: { recipeId: "robe-runique" } } },
    ],
  },
  {
    id: "kael-marchand-jetons",
    name: "Kael",
    title: "Marchand de médailles",
    portrait: "🎖️",
    kind: "marchand",
    rarity: "rare",
    greeting: "Des médailles de héros tombés. Elles ont encore du pouvoir… et un vague parfum de tombe.",
    offers: [
      { id: "jeton", label: "Jeton de rang", cost: { gold: 250 }, reward: { rankTokens: 1 } },
      { id: "jetons", label: "Trois jetons de rang", cost: { gold: 650, resources: { essence: 5 } }, reward: { rankTokens: 3 } },
    ],
  },
  {
    id: "dame-velours",
    name: "Dame Velours",
    title: "Receleuse",
    portrait: "🦹",
    kind: "marchand",
    rarity: "rare",
    greeting: "Ne me demandez pas d'où ça vient. Je ne vous demande pas où vous allez.",
    offers: [
      { id: "rare", label: "Lame « tombée d'un chariot »", description: "Rareté rare garantie.", cost: { gold: 260 }, reward: { item: { recipeId: "hache-d-acier", rarity: "rare" } } },
      { id: "anneau-rare", label: "Anneau volé à un baron", description: "Rareté rare garantie.", cost: { gold: 200 }, reward: { item: { recipeId: "anneau-de-cuivre", rarity: "rare" } } },
    ],
  },
  {
    id: "ragnar-maitre-forge",
    name: "Ragnar",
    title: "Maître-forgeron du Nord",
    portrait: "🔨",
    kind: "marchand",
    rarity: "rare",
    greeting: "Mes pièces ne se vendent pas. Elles se méritent. Mais l'or aide à mériter.",
    offers: [
      { id: "lame", label: "Lame runique", cost: { gold: 380, resources: { ore: 10, essence: 6 } }, reward: { item: { recipeId: "lame-runique" } } },
      { id: "harnois", label: "Harnois du bastion", cost: { gold: 380, resources: { ore: 14, wood: 4 } }, reward: { item: { recipeId: "harnois-du-bastion" } } },
    ],
  },
  {
    id: "noctis-astrologue",
    name: "Noctis",
    title: "Astrologue",
    portrait: "🔭",
    kind: "marchand",
    rarity: "rare",
    greeting: "Les étoiles m'ont dit que vous viendriez. Elles m'ont aussi dit votre budget.",
    offers: [
      { id: "talisman", label: "Talisman astral", cost: { gold: 360, resources: { essence: 10 } }, reward: { item: { recipeId: "talisman-astral" } } },
      { id: "poussiere", label: "Poussière d'étoile", cost: { gold: 200 }, reward: { resources: { essence: 18 } } },
    ],
  },
  {
    id: "zabar-caravanier",
    name: "Zabar",
    title: "Caravanier du désert",
    portrait: "🐪",
    kind: "marchand",
    rarity: "commun",
    greeting: "Ma caravane repart ce soir. Ce qui n'est pas vendu part avec elle.",
    offers: [
      { id: "cargaison", label: "Cargaison complète", cost: { gold: 260 }, reward: { resources: { wood: 15, ore: 15, essence: 6 } } },
      { id: "revente", label: "Revendre du minerai", cost: { resources: { ore: 20 } }, reward: { gold: 110 } },
      { id: "revente-bois", label: "Revendre du bois", cost: { resources: { wood: 20 } }, reward: { gold: 110 } },
    ],
  },
  {
    id: "vieux-fenwick",
    name: "Vieux Fenwick",
    title: "Brocanteur",
    portrait: "🕰️",
    kind: "marchand",
    rarity: "commun",
    greeting: "Tout a de la valeur ici. Surtout ce qui n'en a pas l'air.",
    offers: [
      { id: "coffre", label: "Vieux coffre fermé", description: "Personne n'a la clé. Sauf vous, désormais.", cost: { gold: 120 }, reward: { gold: 60, forgeShards: 5, resources: { essence: 3 } } },
      { id: "babiole", label: "Babiole poussiéreuse", cost: { gold: 35 }, reward: { item: { recipeId: "anneau-de-cuivre" } } },
    ],
  },
  {
    id: "aurelia-marchande-royale",
    name: "Aurélia",
    title: "Fournisseuse de la Couronne",
    portrait: "👑",
    kind: "marchand",
    rarity: "legendaire",
    greeting: "Je ne descends dans les tavernes qu'une fois par lune. Ne me faites pas regretter le voyage.",
    offers: [
      { id: "epique", label: "Lame runique de la garde royale", description: "Rareté épique garantie.", cost: { gold: 900, resources: { ore: 10 } }, reward: { item: { recipeId: "lame-runique", rarity: "epique" } } },
      { id: "talisman-epique", label: "Talisman de la reine", description: "Rareté épique garantie.", cost: { gold: 900, resources: { essence: 10 } }, reward: { item: { recipeId: "talisman-astral", rarity: "epique" } } },
      { id: "cristaux", label: "Coffret de cristaux", cost: { gold: 1200 }, reward: { crystals: 5 } },
    ],
  },

  // ─────────────────────────── Conteurs ───────────────────────────
  {
    id: "barde-lysandre",
    name: "Lysandre",
    title: "Barde errant",
    portrait: "🪕",
    kind: "conteur",
    rarity: "commun",
    greeting: "Assieds-toi, l'ami. Je connais une chanson sur un gobelin qui voulait être roi.",
    story: [
      "Il y a longtemps, à la Lisière de la forêt, vivait un gobelin nommé Grik. Plus petit que les autres, plus malin aussi. Il avait remarqué une chose : les gobelins obéissent toujours à celui qui porte la plus grosse couronne.",
      "Alors Grik vola une marmite à un aubergiste, la retourna sur sa tête, et se proclama Chef. Personne n'osa le contredire — la marmite était vraiment très grosse.",
      "Il paraît que chaque Chef gobelin, depuis, porte une marmite. Et que chaque aubergiste de la région garde la sienne enchaînée au comptoir. Regarde derrière le bar : tu verras la chaîne.",
    ],
  },
  {
    id: "grand-mere-oda",
    name: "Grand-mère Oda",
    title: "Doyenne du village",
    portrait: "👵",
    kind: "conteur",
    rarity: "commun",
    greeting: "Ah, un jeune aventurier. Tu me rappelles mon troisième mari. Il est mort, lui aussi.",
    story: [
      "Quand j'étais petite, les Mines n'étaient pas abandonnées. On y entendait chanter les nains du matin au soir. Puis un jour, ils ont creusé trop profond et ont réveillé quelque chose de pierre.",
      "Le Golem ancien n'est pas méchant, vois-tu. Il protège. Seulement, il ne sait plus ce qu'il protège, alors il protège tout. Contre tout le monde.",
      "Si un jour tu l'affrontes, parle-lui avant de frapper. Ça ne servira à rien, mais c'est poli.",
    ],
  },
  {
    id: "frere-anselme",
    name: "Frère Anselme",
    title: "Moine copiste",
    portrait: "🕯️",
    kind: "conteur",
    rarity: "commun",
    greeting: "J'ai recopié mille livres. Un seul m'a fait peur. Veux-tu savoir lequel ?",
    story: [
      "Dans la bibliothèque des Ruines oubliées, il y avait un livre sans titre. Ceux qui l'ouvraient n'y lisaient que leur propre nom, écrit encore et encore, de plus en plus serré.",
      "Un novice curieux le lut jusqu'à la dernière page. On raconte qu'à la dernière ligne, son nom s'arrêtait au milieu. Il n'est jamais ressorti des Ruines.",
      "Les araignées tissent aujourd'hui leurs toiles entre les étagères. Certains disent qu'elles protègent le livre. Moi, je crois qu'elles le lisent.",
    ],
  },
  {
    id: "capitaine-mordrek",
    name: "Capitaine Mordrek",
    title: "Vétéran unijambiste",
    portrait: "🦿",
    kind: "conteur",
    rarity: "commun",
    greeting: "Tu veux savoir comment j'ai perdu ma jambe ? Paie-moi… non, laisse. Je te le dis gratis.",
    story: [
      "C'était dans un donjon, un de ces trous que les seigneurs remplissent de pièges pour protéger leur or. Mon escouade avait nettoyé trois salles. Trois ! On se croyait invincibles.",
      "La quatrième était vide. Totalement vide. J'aurais dû comprendre : une salle vide dans un donjon, c'est une salle qui attend quelqu'un. Une fosse à pieux s'est ouverte sous moi.",
      "Leçon du jour, petit : quand ton butin est en banque, rentre chez toi. Les morts ne dépensent pas leur or.",
    ],
  },
  {
    id: "elwen-elfe",
    name: "Elwen",
    title: "Éclaireuse elfe",
    portrait: "🏹",
    kind: "conteur",
    rarity: "commun",
    greeting: "Les humains boivent trop vite. Laisse-moi te raconter quelque chose de lent.",
    story: [
      "Les premiers archers n'utilisaient pas de flèches. Ils tiraient des chants. Une note assez juste pouvait fendre une pierre, disait-on.",
      "Puis les chanteurs ont vieilli, leurs voix se sont brisées, et il a fallu trouver autre chose. On a taillé du bois, on y a mis des plumes, et on a appelé ça un progrès.",
      "Quand tu verras un archer fredonner avant de tirer, ne te moque pas. Il essaie de se souvenir.",
    ],
  },
  {
    id: "maitre-ombrelune",
    name: "Maître Ombrelune",
    title: "Nécromancien repenti",
    portrait: "💀",
    kind: "conteur",
    rarity: "rare",
    greeting: "Oui, j'ai fait des choses. Non, je ne les referai plus. Enfin, probablement pas.",
    story: [
      "La Nécropole maudite n'a pas toujours été maudite. C'était un cimetière comme un autre, où l'on enterrait les gens avec respect et un peu trop de bijoux.",
      "Le Seigneur des ombres était un simple gardien, payé trois pièces par nuit pour chasser les pilleurs. Un hiver, on oublia de le payer. Puis on oublia de le relever. Puis on l'oublia tout court.",
      "Il garde toujours le cimetière. Il a juste décidé que les vivants en faisaient partie. Si tu y vas, emporte trois pièces. On ne sait jamais.",
    ],
  },
  {
    id: "tante-berthe",
    name: "Tante Berthe",
    title: "Cuisinière de la taverne",
    portrait: "🍲",
    kind: "conteur",
    rarity: "commun",
    greeting: "Tu ne manges pas assez. Tiens, prends une soupe, et écoute.",
    story: [
      "Le secret de ma soupe ? Un os de golem d'ossements. Ça donne du goût, et ça fait peur aux rats.",
      "Un jour, un paladin est venu la goûter. Il a pleuré. Il m'a dit que c'était la soupe de sa mère. Je lui ai demandé si sa mère utilisait des os de golem. Il est parti sans payer.",
      "Depuis, je la fais tous les jeudis. Il revient tous les jeudis. Il ne paie toujours pas.",
    ],
  },
  {
    id: "sage-thalos",
    name: "Thalos",
    title: "Sage aveugle",
    portrait: "🧿",
    kind: "conteur",
    rarity: "rare",
    greeting: "Je ne vois pas ton visage, mais j'entends ton épée. Elle est fatiguée.",
    story: [
      "Il existait six chemins pour devenir héros : la lame, l'arc, la prière, la nature, le serment et la montagne. Chaque chemin avait son gardien, et chaque gardien exigeait un prix.",
      "Le Guerrier donnait sa peur. L'Archer, sa patience. Le Prêtre, son doute. Le Druide, sa maison. Le Paladin, sa liberté. Et le Colosse… le Colosse donnait sa douceur, et c'est pourquoi on ne le prend jamais dans ses bras.",
      "Aujourd'hui, on dit que les chemins se tirent au hasard, comme on tire une carte. Les gardiens trouvent ça très drôle.",
    ],
  },
  {
    id: "petit-lou",
    name: "Petit Lou",
    title: "Garçon d'écurie",
    portrait: "🧒",
    kind: "conteur",
    rarity: "commun",
    greeting: "M'sieur, m'sieur ! Vous voulez savoir un secret ? C'est un vrai de vrai !",
    story: [
      "Mon grand frère, il dit qu'il y a un donjon où toutes les salles sont des trésors. Toutes ! Même les couloirs, ils sont en or.",
      "Mais personne n'y est jamais allé, parce que l'entrée, elle est dans le ventre d'un dragon. Et le dragon, il dort sur l'entrée. Alors faut attendre qu'il se réveille, mais s'il se réveille, il vous mange.",
      "Mon frère dit que c'est un paradoxe. Je sais pas ce que c'est, mais ça a l'air dangereux.",
    ],
  },
  {
    id: "dame-isaure",
    name: "Dame Isaure",
    title: "Veuve en noir",
    portrait: "🥀",
    kind: "conteur",
    rarity: "commun",
    greeting: "Mon mari était aventurier. Asseyez-vous, je vais vous dire comment il est parti.",
    story: [
      "Il est parti en expédition un matin, avec trois compagnons et beaucoup trop de confiance. Il m'a promis d'être rentré avant la soupe.",
      "Il n'est pas mort, rassurez-vous. Il a rencontré la Reine des araignées, et elle l'a trouvé charmant. Il vit dans les Ruines, maintenant. Il m'écrit parfois. Sur de la soie.",
      "Si vous le croisez, dites-lui que la soupe est froide.",
    ],
  },
  {
    id: "vieux-marin-tobbe",
    name: "Tobbe",
    title: "Vieux loup de mer",
    portrait: "⚓",
    kind: "conteur",
    rarity: "commun",
    greeting: "Y a pas de mer ici, je sais. C'est bien pour ça que je suis venu.",
    story: [
      "J'ai navigué quarante ans. J'ai vu des serpents de mer, des sirènes, des îles qui étaient en fait des tortues. Rien de tout ça ne m'a fait peur.",
      "Mais une nuit, on a pêché un coffre. Dedans, il y avait une carte. Sur la carte, il y avait notre bateau. Et sur le bateau, un petit point qui bougeait, et qui venait vers nous.",
      "J'ai jeté la carte par-dessus bord. Le point s'est arrêté. Depuis, je vis à terre, loin de toute eau, et je ne lis plus jamais de carte.",
    ],
  },
  {
    id: "orc-grundak",
    name: "Grundak",
    title: "Orc pacifiste",
    portrait: "🌿",
    kind: "conteur",
    rarity: "rare",
    greeting: "Grundak pas taper. Grundak raconter. C'est mieux pour tout le monde.",
    story: [
      "Grundak était éclaireur orc. Grundak courait devant, trouvait les ennemis, revenait, et les autres tapaient. Grundak trouvait ça fatigant.",
      "Un jour, Grundak a trouvé un village. Au lieu de revenir, Grundak est entré. Une vieille dame lui a donné une tarte. Personne n'avait jamais donné de tarte à Grundak.",
      "Maintenant Grundak fait les tartes. Le chaman dit que Grundak est une honte. Mais le chaman vient manger les tartes le dimanche.",
    ],
  },
  {
    id: "chroniqueur-alaric",
    name: "Alaric",
    title: "Chroniqueur royal",
    portrait: "📜",
    kind: "conteur",
    rarity: "commun",
    greeting: "J'écris l'histoire des héros. Pour l'instant, la vôtre tient sur une ligne.",
    story: [
      "Savez-vous pourquoi les héros d'aujourd'hui commencent sans rien ? Ni classe, ni sort, ni talent ? C'est la faute du Grand Oubli.",
      "Un sorcier jaloux jeta un sort sur tout le royaume : chaque héros oublierait tout ce qu'il savait. Les maîtres d'armes ne savaient plus tenir une épée, les prêtres ne savaient plus prier.",
      "Mais le savoir ne disparaît pas, il se disperse. Il flotte dans les cristaux d'invocation, en morceaux. Chaque fois que vous en brisez un, vous récupérez un fragment de ce qui fut. Pas mal pour une punition, non ?",
    ],
  },
  {
    id: "liche-endormie",
    name: "Morvaine",
    title: "Liche à la retraite",
    portrait: "🦴",
    kind: "conteur",
    rarity: "legendaire",
    greeting: "Ne criez pas. Je suis à la retraite. Je bois juste mon thé. Il est froid, comme moi.",
    story: [
      "Pendant six siècles, j'ai commandé les ombres. J'ai eu des armées, des donjons, une tour avec vue sur un volcan. Et vous savez ce qui m'a fait arrêter ? Les impôts.",
      "Même mort, on vous taxe. Taxe sur les donjons, taxe sur les squelettes, taxe sur les malédictions de plus de trois générations. J'ai tout vendu à un jeune Seigneur des ombres plein d'ambition.",
      "Il m'envoie une carte à chaque solstice. Il a l'air épuisé. C'est la vie. Enfin, façon de parler.",
    ],
    offers: [
      { id: "pourboire", label: "Accepter son vieux phylactère", description: "« Il ne me sert plus. Il reste un peu de magie dedans. »", reward: { crystals: 3, resources: { essence: 10 } } },
    ],
  },
  {
    id: "jumeaux-fil",
    name: "Fil & Fila",
    title: "Jumeaux conteurs",
    portrait: "🎭",
    kind: "conteur",
    rarity: "commun",
    greeting: "— On raconte à deux voix. — Mais pas la même histoire. — Choisis celle que tu préfères.",
    story: [
      "— Il était une fois un druide qui parlait aux arbres. — Non, il était une fois un arbre qui parlait aux druides.",
      "— Le druide demanda à l'arbre de pousser plus vite. — L'arbre demanda au druide de marcher moins vite.",
      "— Ils ne se sont jamais mis d'accord. — Et c'est pour ça que les druides sont lents et les arbres impatients. — Fin. — Ce n'est pas la fin. — Si.",
    ],
  },
  {
    id: "espionne-nyx",
    name: "Nyx",
    title: "Espionne en congé",
    portrait: "🕵️",
    kind: "conteur",
    rarity: "rare",
    greeting: "Je ne suis pas là. Vous ne m'avez pas vue. Mais je peux vous dire un truc.",
    story: [
      "J'ai visité des dizaines de donjons de joueurs. Discrètement, bien sûr. Et je peux vous dire une chose : la plupart des gens mettent leur trésor tout au fond.",
      "Les malins, eux, en mettent un près de l'entrée, bien visible, pour que l'attaquant croie avoir gagné et reparte. Et le vrai trésor dort derrière trois salles de gaz toxique.",
      "Les très malins mettent des monstres dans les couloirs vides. Parce que tout le monde baisse sa garde dans un couloir vide. Je ne vous ai rien dit.",
    ],
  },

  // ─────────────────────────── Bienfaiteurs ───────────────────────────
  {
    id: "frere-gaspard",
    name: "Frère Gaspard",
    title: "Moine mendiant",
    portrait: "🙏",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "Les dieux m'ont donné plus qu'il ne m'en faut. Prends, mon enfant.",
    offers: [{ id: "aumone", label: "Recevoir l'aumône", reward: { gold: 80 } }],
  },
  {
    id: "marraine-flora",
    name: "Marraine Flora",
    title: "Bonne fée un peu distraite",
    portrait: "🧚",
    kind: "bienfaiteur",
    rarity: "rare",
    greeting: "Un vœu ! Tu as droit à un vœu ! Enfin, un petit. Les grands sont en rupture de stock.",
    offerMode: "pickOne",
    offers: [
      { id: "or", label: "La richesse", reward: { gold: 250 } },
      { id: "cristaux", label: "La magie", reward: { crystals: 2 } },
      { id: "force", label: "La force", reward: { rankTokens: 2 } },
    ],
  },
  {
    id: "sergent-bram",
    name: "Sergent Bram",
    title: "Recruteur de la milice",
    portrait: "🪖",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "La milice soutient les aventuriers ! Voici votre paquetage réglementaire.",
    offers: [{ id: "paquetage", label: "Prendre le paquetage", reward: { gold: 40, resources: { wood: 6, ore: 6 } } }],
  },
  {
    id: "enfant-perdu",
    name: "Mila",
    title: "Enfant perdue",
    portrait: "👧",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "J'ai trouvé ça dans la forêt. C'est brillant. Tu le veux ? Je préfère les cailloux ronds.",
    offers: [{ id: "caillou", label: "Accepter la pierre brillante", reward: { resources: { essence: 6 } } }],
  },
  {
    id: "baron-gilbert",
    name: "Baron Gilbert",
    title: "Noble généreux (et ivre)",
    portrait: "🍷",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "Tournée générale ! Et pour vous, mon brave, une bourse ! Hips !",
    offers: [{ id: "bourse", label: "Attraper la bourse au vol", reward: { gold: 120 } }],
  },
  {
    id: "druidesse-alma",
    name: "Alma",
    title: "Druidesse des chênes",
    portrait: "🌳",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "La forêt a eu une bonne saison. Elle partage.",
    offerMode: "pickOne",
    offers: [
      { id: "bois", label: "Bois de chêne", reward: { resources: { wood: 15 } } },
      { id: "seve", label: "Sève enchantée", reward: { resources: { essence: 6 } } },
    ],
  },
  {
    id: "forgeron-retraite",
    name: "Old Hamm",
    title: "Forgeron à la retraite",
    portrait: "🧓",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "Mes mains tremblent trop pour forger. Prends mes réserves, elles seront mieux chez toi.",
    offers: [{ id: "reserves", label: "Hériter de ses réserves", reward: { forgeShards: 10, resources: { ore: 5 } } }],
  },
  {
    id: "pelerin-mystere",
    name: "Le Pèlerin",
    title: "Voyageur encapuchonné",
    portrait: "🧥",
    kind: "bienfaiteur",
    rarity: "rare",
    greeting: "Je t'observe depuis un moment. Tu iras loin. Tiens, pour le voyage.",
    offers: [{ id: "cristaux", label: "Recevoir sa bénédiction", reward: { crystals: 2, gold: 50 } }],
  },
  {
    id: "maitre-darius",
    name: "Maître Darius",
    title: "Instructeur d'armes",
    portrait: "⚔️",
    kind: "bienfaiteur",
    rarity: "rare",
    greeting: "Tes héros ont du potentiel. Ce qu'il leur manque, c'est de la discipline. Et des médailles.",
    offers: [{ id: "medailles", label: "Recevoir ses médailles", reward: { rankTokens: 2 } }],
  },
  {
    id: "coffre-parlant",
    name: "Coffre-qui-parle",
    title: "Mimique repentie",
    portrait: "📦",
    kind: "bienfaiteur",
    rarity: "rare",
    greeting: "Avant je mangeais les aventuriers. Maintenant je suis végétarien. Ouvre-moi, je ne mords plus.",
    offerMode: "pickOne",
    offers: [
      { id: "ouvrir", label: "L'ouvrir (confiance)", description: "Un vrai trésor… normalement.", reward: { item: { recipeId: "cotte-de-mailles", rarity: "rare" } } },
      { id: "secouer", label: "Le secouer (prudence)", description: "Il en tombe quelques pièces.", reward: { gold: 150 } },
    ],
  },
  {
    id: "chat-noir",
    name: "Minuit",
    title: "Chat de la taverne",
    portrait: "🐈‍⬛",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "Mrrrow. (Le chat dépose quelque chose à tes pieds et te fixe intensément.)",
    offers: [{ id: "cadeau", label: "Ramasser son « cadeau »", description: "Ce n'est pas une souris. C'est… un éclat de forge ?", reward: { forgeShards: 6, gold: 20 } }],
  },
  {
    id: "pretresse-soline",
    name: "Soline",
    title: "Prêtresse du soleil",
    portrait: "☀️",
    kind: "bienfaiteur",
    rarity: "commun",
    greeting: "Le soleil brille pour tout le monde. Aujourd'hui, un peu plus pour toi.",
    offerMode: "pickOne",
    offers: [
      { id: "offrande", label: "Les offrandes du temple", reward: { gold: 100 } },
      { id: "cierge", label: "Un cierge béni", reward: { resources: { essence: 5 } } },
    ],
  },
  {
    id: "dragon-deguise",
    name: "Monsieur Braise",
    title: "Gentilhomme très, très chaud",
    portrait: "🐉",
    kind: "bienfaiteur",
    rarity: "legendaire",
    greeting: "Je ne suis absolument pas un dragon. Mais si j'en étais un, j'aurais un trésor à partager.",
    offerMode: "pickOne",
    offers: [
      { id: "tresor", label: "Une poignée du trésor", reward: { crystals: 6 } },
      { id: "ecaille", label: "Une écaille « tombée par hasard »", description: "Rareté légendaire garantie.", reward: { item: { recipeId: "harnois-du-bastion", rarity: "legendaire" } } },
      { id: "or", label: "Tout l'or que tu peux porter", reward: { gold: 1500 } },
    ],
  },
  {
    id: "gardien-cristaux",
    name: "Éléonore",
    title: "Gardienne des cristaux",
    portrait: "💎",
    kind: "bienfaiteur",
    rarity: "legendaire",
    greeting: "Les cristaux choisissent leur porteur. Ceux-ci t'ont choisi. Je n'y peux rien.",
    offers: [{ id: "cristaux", label: "Recevoir les cristaux", reward: { crystals: 5, rankTokens: 1 } }],
  },

  // ─────────────────────────── Parieurs ───────────────────────────
  {
    id: "lucky-joe",
    name: "Joe-la-Chance",
    title: "Joueur de dés",
    portrait: "🎲",
    kind: "parieur",
    rarity: "commun",
    greeting: "Un petit lancer ? Pair, tu gagnes. Impair, je gagne. Zéro, on recommence. Il n'y a pas de zéro.",
    winLine: "Pair ! Bon, d'accord, tu as gagné. Prends ton or et va-t'en avant que je change d'avis.",
    loseLine: "Impair. Pas de chance, l'ami. Ce sera pour la prochaine !",
    offers: [
      { id: "petit", label: "Petite mise", cost: { gold: 50 }, reward: { gold: 100 }, winChance: 0.5 },
      { id: "gros", label: "Grosse mise", cost: { gold: 200 }, reward: { gold: 400 }, winChance: 0.5 },
    ],
  },
  {
    id: "madame-zora",
    name: "Madame Zora",
    title: "Diseuse de bonne aventure",
    portrait: "🔮",
    kind: "parieur",
    rarity: "commun",
    greeting: "Tire une carte, et le destin te récompensera. Ou pas. Le destin est capricieux.",
    winLine: "La Roue de Fortune ! Le destin te sourit aujourd'hui.",
    loseLine: "La Tour… Ce n'est pas ton jour. Mais les cartes, elles, ne mentent jamais.",
    offers: [
      { id: "carte", label: "Tirer une carte", cost: { gold: 120 }, reward: { crystals: 1 }, winChance: 0.35 },
    ],
  },
  {
    id: "bras-de-fer",
    name: "Olga",
    title: "Championne de bras de fer",
    portrait: "💪",
    kind: "parieur",
    rarity: "commun",
    greeting: "Personne ne m'a battue depuis trois hivers. Tu veux tenter ta chance ? Ça coûte cher de perdre.",
    winLine: "Qu… QUOI ?! Personne ne m'avait jamais… Bon. Voilà ta récompense. N'en parle à personne.",
    loseLine: "Crac ! Tu garderas le bras, rassure-toi. Mais pas ta mise.",
    offers: [
      { id: "duel", label: "Défier Olga", cost: { gold: 100 }, reward: { gold: 350 }, winChance: 0.3 },
    ],
  },
  {
    id: "coquilles",
    name: "Filou",
    title: "Joueur de bonneteau",
    portrait: "🥜",
    kind: "parieur",
    rarity: "commun",
    greeting: "Trois gobelets, une bille. Suis-la bien… hop hop hop ! Alors, elle est où ?",
    winLine: "Celui du milieu ?! Mais comment… Tu as triché. Non ? Bon, prends tes gains.",
    loseLine: "Raté ! Elle était dans ma manche. Euh, sous celui de gauche, je veux dire.",
    offers: [
      { id: "gobelet", label: "Choisir un gobelet", cost: { gold: 60 }, reward: { gold: 180 }, winChance: 0.33 },
      { id: "minerai", label: "Miser du minerai", cost: { resources: { ore: 10 } }, reward: { resources: { ore: 30 } }, winChance: 0.33 },
    ],
  },
  {
    id: "mineur-ivre",
    name: "Dorgal",
    title: "Mineur éméché",
    portrait: "🍺",
    kind: "parieur",
    rarity: "commun",
    greeting: "Je parie que tu peux pas boire plus que moi ! Allez, une chope, et si t'es encore debout, je te donne mes éclats !",
    winLine: "T'es… hic… encore debout ?! Bravo… prends… prends tout… (il s'endort sur la table)",
    loseLine: "Hahaha ! Sous la table ! Merci pour la tournée, l'ami !",
    offers: [
      { id: "chope", label: "Relever le défi", cost: { gold: 80 }, reward: { forgeShards: 15 }, winChance: 0.45 },
    ],
  },
  {
    id: "loterie-gnome",
    name: "Tik-Tak",
    title: "Gnome organisateur de loterie",
    portrait: "🎟️",
    kind: "parieur",
    rarity: "rare",
    greeting: "Loterie mécanique ! Un ticket, une manivelle, et peut-être le gros lot ! Garanti sans arnaque à 60 % !",
    winLine: "Ding ding ding ! Gros lot ! La machine n'a explosé qu'un tout petit peu !",
    loseLine: "Ticket perdant. La machine vous remercie de votre contribution.",
    offers: [
      { id: "ticket", label: "Acheter un ticket", cost: { gold: 150 }, reward: { crystals: 3 }, winChance: 0.2 },
      { id: "essence", label: "Ticket à l'essence", cost: { resources: { essence: 5 } }, reward: { crystals: 2 }, winChance: 0.3 },
    ],
  },
  {
    id: "chevalier-noir",
    name: "Chevalier sans nom",
    title: "Duelliste en armure noire",
    portrait: "🗡️",
    kind: "parieur",
    rarity: "rare",
    greeting: "Ton plus fort héros contre moi. Si tu gagnes, mon armure est à toi. Si tu perds… ton or sera à moi.",
    winLine: "…Bien joué. Prends-la. Elle ne m'a jamais porté chance de toute façon.",
    loseLine: "Trop lent. Reviens quand tes héros auront pris quelques étoiles.",
    offers: [
      { id: "duel", label: "Accepter le duel", cost: { gold: 300 }, reward: { item: { recipeId: "harnois-du-bastion", rarity: "epique" } }, winChance: 0.3 },
    ],
  },
  {
    id: "fortune-dore",
    name: "Le Maître des Jeux",
    title: "Croupier d'outre-monde",
    portrait: "🃏",
    kind: "parieur",
    rarity: "legendaire",
    greeting: "Un seul jeu, une seule fois. Le prix est élevé. La récompense… l'est davantage.",
    winLine: "Le destin s'incline devant toi. Profite de ta chance — elle ne repasse pas souvent.",
    loseLine: "La maison gagne toujours. Enfin, presque toujours. Ce n'était pas cette fois.",
    offers: [
      { id: "grand-jeu", label: "Jouer le grand jeu", cost: { gold: 500 }, reward: { crystals: 10 }, winChance: 0.4 },
      { id: "petit-jeu", label: "Jouer prudemment", cost: { gold: 150 }, reward: { crystals: 3 }, winChance: 0.4 },
    ],
  },

  // ─────────────────────────── PNJ personnalisés ───────────────────────────
  {
    id: "loup-lune",
    name: "Loup Lune",
    title: "Puriste du beau jeu",
    portrait: "🐺",
    kind: "conteur",
    rarity: "rare",
    greeting: "Assieds-toi. Non, pas sur ce tabouret-là, tout le monde s'assoit sur celui-là. Prends le bancal. C'est plus beau.",
    story: [
      "Je vais te parler d'un mal qui ronge les aventuriers. Il n'a pas de crocs, pas de griffes, il ne rôde pas dans la Nécropole. Il se cache dans les conversations de taverne, entre deux chopes. On l'appelle « la méta ».",
      "Tu l'as déjà entendue, sa voix. « Prends Guerrier, mets les deux mêmes sorts que tout le monde, équipe la Lame runique, c'est le meilleur rapport. » Et les jeunes hochent la tête. Et ils partent tous avec la même épée, le même sort, la même tête. Des milliers de héros, et une seule idée.",
      "Moi, j'appelle ça jouer en copiant la copie d'un autre. Tu gagnes, oui. Mais qu'est-ce que tu gagnes, au fond ? Une victoire que quelqu'un d'autre a déjà remportée à ta place, avant même que tu sortes ta lame.",
      "Le beau jeu, c'est autre chose. Le beau jeu, c'est le type qui entre dans les Mines avec un Druide équipé d'une Hache d'acier et d'un anneau de cuivre parce qu'il trouvait que ça allait bien avec ses yeux. C'est l'archère qui s'obstine avec une robe runique alors qu'elle n'a pas un gramme de magie dans le corps.",
      "Est-ce que c'est efficace ? Non. Absolument pas. Ils meurent souvent, ils meurent bêtement, et on se moque d'eux. Mais le jour où ce Druide à la hache abat le Golem ancien, crois-moi, toute la taverne en parle pendant un mois. Personne ne parle du centième Guerrier qui a fait la même chose en suivant le guide.",
      "Alors va chercher l'objet que personne ne regarde. L'affixe bizarre, celui qui donne de la vitesse et retire de la défense. Le bâton que tout le monde recycle. Fais-le marcher. Force-le à marcher. C'est là que tu deviendras un vrai joueur.",
      "Et si tu perds ? Tu auras perdu avec panache. C'est la seule défaite qui compte. Maintenant va, et si je te vois avec la Lame runique, je fais semblant de ne pas te connaître.",
    ],
  },
  {
    id: "le-magnifique",
    name: "Le Magnifique",
    title: "Couturier des interfaces",
    portrait: "🦚",
    kind: "marchand",
    rarity: "rare",
    greeting: "Votre monde est si… terne. Laissez-moi le repeindre. Choisissez une couleur, je m'occupe du reste. Effet garanti. Enfin, un effet.",
    offers: [
      { id: "rubis", label: "Rouge rubis", description: "Une interface flamboyante.", cost: { gold: 15 }, reward: { cosmeticThemeId: "rubis" } },
      { id: "emeraude", label: "Vert émeraude", description: "La fraîcheur de la Lisière.", cost: { gold: 15 }, reward: { cosmeticThemeId: "emeraude" } },
      { id: "saphir", label: "Bleu saphir", description: "Le calme des profondeurs.", cost: { gold: 15 }, reward: { cosmeticThemeId: "saphir" } },
      { id: "amethyste", label: "Violet améthyste", description: "Le mystère des arcanes.", cost: { gold: 15 }, reward: { cosmeticThemeId: "amethyste" } },
      { id: "or", label: "Or royal", description: "Digne de la Couronne.", cost: { gold: 15 }, reward: { cosmeticThemeId: "or" } },
    ],
  },
  {
    id: "faucon",
    name: "Faucon",
    title: "Richissime (fauché)",
    portrait: "🦅",
    kind: "conteur",
    rarity: "rare",
    greeting: "Tu peux m'offrir une chope ? Je te rembourse. Je suis riche, hein. Très riche. Juste… pas là, maintenant.",
    story: [
      "Laisse-moi t'expliquer, parce que les gens ne comprennent pas. Je suis l'un des aventuriers les plus riches du royaume. J'ai pillé plus de donjons que tu n'as mangé de soupes de Tante Berthe. L'or me coule entre les doigts.",
      "Le problème, c'est justement qu'il coule. Parce qu'un vrai aventurier, ça ne se contente pas d'une épée. Il faut l'épée de feu pour les golems, l'épée de glace pour les araignées, et l'épée de secours au cas où l'épée de secours casse.",
      "Et les armures ! Une pour le jour, une pour la nuit, une pour les raids, une pour les expéditions, une pour les mardis. Plus trois anneaux par doigt, au cas où. Tu savais qu'on n'a que dix doigts ? Moi j'ai acheté trente-deux anneaux avant de m'en rendre compte.",
      "Hier, j'ai rapporté mille pièces d'or des Ruines. Ce matin, un marchand m'a montré une cape avec un affixe de vitesse. Une cape ! Je n'avais pas de cape. Enfin, j'en avais six, mais pas avec CET affixe-là.",
      "Alors voilà. Je suis riche, c'est certain. Mon coffre déborde d'équipement. J'ai juste zéro pièce dans la bourse. C'est ce qu'on appelle un investissement. Tu me l'offres, cette chope ?",
    ],
  },
  {
    id: "zz-leventreur",
    name: "ZZ l'Éventreur",
    title: "Prisonnier de l'Ombre",
    portrait: "🌘",
    kind: "conteur",
    rarity: "rare",
    storyLoops: true,
    greeting: "Ah… c'est toi. Ou c'était toi ? J'étais en train de… Non. Attends. Je me souviens. Je crois.",
    story: [
      "Avant, c'était mieux, tu sais. Avant, les donjons avaient de vraies salles, les monstres avaient de vrais crocs, et moi j'avais un vrai nom. Maintenant je suis ZZ. Juste ZZ. Même mon nom a été raccourci.",
      "Tu vois la lune, là-haut ? Je la regarde souvent. Des heures. Parfois je pars dedans sans le vouloir, je pense à la Nécropole d'il y a dix ans, aux raids qu'on faisait à l'époque, et quand je reviens, ma chope est vide et il fait jour.",
      "Je suis coincé dans un endroit qui s'appelle l'Ombre. Pas les ombres de la Nécropole. L'Ombre. Un lieu tout gris, où il n'y a qu'une seule salle, un seul monstre, et une seule chose à faire.",
      "Alors je le fais. J'entre, je frappe, il tombe. Je sors. Et puis je rentre. Je frappe. Il tombe. Je sors. Je rentre. Je frappe. Il tombe…",
      "Pourquoi je te raconte ça, déjà ? Ah… c'est toi. Ou c'était toi ? Laisse-moi recommencer depuis le début.",
    ],
  },
  {
    id: "dieu",
    name: "Dieu",
    title: "En personne, oui",
    portrait: "☁️",
    kind: "bienfaiteur",
    rarity: "legendaire",
    greeting: "Mon enfant. Je t'offre un présent tiré de ma création. En échange, tu me donneras une offrande. Combien ? Tu le sauras après. C'est ça, la foi.",
    offers: [
      {
        id: "offrande",
        label: "Faire une offrande",
        description: "Un objet au hasard, de n'importe quelle rareté. Le prix : entre 1 pièce d'or et tout ce que tu possèdes.",
        randomGoldCost: true,
        reward: { randomItem: true },
      },
    ],
  },
];

/** Le Magnifique's joke themes: a CSS filter applied to the whole page while it's open.
 *  The player never gets the one they picked (see app/(game)/taverne/page.tsx). */
export interface CosmeticTheme {
  id: string;
  name: string;
  filter: string;
}

export const COSMETIC_THEMES: CosmeticTheme[] = [
  { id: "rubis", name: "Rouge rubis", filter: "hue-rotate(-40deg) saturate(1.6)" },
  { id: "emeraude", name: "Vert émeraude", filter: "hue-rotate(90deg) saturate(1.4)" },
  { id: "saphir", name: "Bleu saphir", filter: "hue-rotate(180deg) saturate(1.3)" },
  { id: "amethyste", name: "Violet améthyste", filter: "hue-rotate(250deg) saturate(1.4)" },
  { id: "or", name: "Or royal", filter: "sepia(0.6) saturate(2) brightness(1.1)" },
  { id: "parchemin", name: "Parchemin jauni", filter: "sepia(1) contrast(0.9)" },
  { id: "fantome", name: "Noir et blanc fantôme", filter: "grayscale(1) contrast(1.1)" },
  { id: "inverse", name: "Monde à l'envers", filter: "invert(1) hue-rotate(180deg)" },
  { id: "psyche", name: "Champignon de la Lisière", filter: "saturate(4) hue-rotate(130deg)" },
];

export function getTavernNpc(id: string): TavernNpc | undefined {
  return TAVERN_NPCS.find((npc) => npc.id === id);
}
